#!/usr/bin/env python

import os

extensions = (".cpp", ".c", ".h", ".hpp")
code_style = "{BasedOnStyle: Google, IndentWidth: 4}"

def format_dir(directory, style):
    for root, _, files in os.walk(directory):
        for file in files:
            if file.endswith(extensions):
                os.system("clang-format -i -style=\"" + style + "\" " + root + "/" + file)

format_dir("source", code_style)
format_dir("include", code_style)
